Feature/taxi
HPlus1100/server pull request #16
Opened 2023-09-26 03:09 UTC by kthss01

## Description
Taxi Feature 입니다.
<br>

## Key Changes

<br>

## Issue Reference

> (Only on Fix and Hotfix branch)

## Package Change

> (Only on Chore branch)

<br>

## Checklist

- [ ] Asignee를 같은 파트원으로 지정했나요?
- [ ] Reviewer를 2명 이상 지정 했나요?
- [ ] 코드의 엣지 케이스에 대해 충분히 고민 하셨나요?
- [ ] conflict가 나지 않는지 확인 하셨나요?

2023-09-26 03:10 UTC, kthss01 commented
현재 commit 시에 전체 코드들이 변경 사항으로 올라오는 이슈가 있는데 이부분 일단은 놔두고 수정사항만 commit 했습니다

2023-10-11 16:55 UTC, ghd64845 commented
해당 PR은 현재 진행 중 인건가요?

2023-10-12 13:51 UTC, kthss01 commented
> 해당 PR은 현재 진행 중 인건가요?

네 현재 테스트 코드 작성도 진행하고 있습니다

2023-10-12 13:51 UTC, kthss01 commented
> 현재 commit 시에 전체 코드들이 변경 사항으로 올라오는 이슈가 있는데 이부분 일단은 놔두고 수정사항만 commit 했습니다

>해당사항은 조치했습니다

2023-10-14 01:13 UTC, kimseungbin requested changes
전체적으로 모듈 이름이 단수처리되어있어 어색한 path 가 생성됩니다.
taxis 로 전체 변경이 필요합니다.

2023-10-14 01:13 UTC, kimseungbin commented on src/taxi/dto/create-taxi.dto.ts
> +  carNum: string;
혹시 license plate number 인가요?
추가적으로 정규표현식 제약이 있으면 좋을 것같아요.

2023-10-14 01:13 UTC, kimseungbin commented on src/taxi/dto/create-taxi.dto.ts
> +  carType: CarType;
Enum 이 정의되거나 todo 로 남아있으면 좋을 것같습니다.

2023-10-14 01:13 UTC, kimseungbin commented on src/taxi/dto/response-taxi.dto.ts
> +  driverNo: number;
이게 다르다는 것은 택시와 기사가 1:1 관계가 아닌 것을 염두에 두신건가요?

2023-10-14 01:13 UTC, kimseungbin commented on src/taxi/taxi.controller.ts
> +  }
Put 이 아닌 Patch 인 이유가 있나요?

2023-10-14 01:13 UTC, kimseungbin commented on src/taxi/taxi.service.spec.ts
> +      .compile();
매번 모듈을 새로 생성해줘야하는 이유는 무엇인가요?

2023-10-14 01:13 UTC, kimseungbin commented on src/taxi/taxi.service.spec.ts
> +    expect(createTaxi.driverNo).toBe(131112345678);
Service test 의 범주에서 벗어납니다.

2023-10-14 01:13 UTC, kimseungbin commented on src/taxi/taxi.service.spec.ts
> +  });
Service test 의 범주에서 벗어납니다.

2023-10-14 01:13 UTC, kimseungbin commented on src/taxi/taxi.service.spec.ts
> +    // TOBO 뭔가 이상함 그냥 plainToClass 안해도 no 같은거 안들어가야할거 같은데 들어감
오타입니다.

2023-10-14 02:21 UTC, kthss01 commented on src/taxi/dto/create-taxi.dto.ts
> +  carNum: string;
license plate number 입니다 정규표현식 부분도 추가하겠습니다

2023-10-14 02:22 UTC, kthss01 commented on src/taxi/dto/create-taxi.dto.ts
> +  carType: CarType;
taxi.enum.ts 에 carType enum으로 정의하고 있습니다

2023-10-14 02:22 UTC, kthss01 commented on src/taxi/dto/response-taxi.dto.ts
> +  driverNo: number;
driverNo는 운전면허증 번호를 의미하고 있습니다. 관계에 있어서는 1:1 관계로 생각하고 있습니다

2023-10-14 02:23 UTC, kthss01 commented on src/taxi/taxi.controller.ts
> +  }
택시 정보를 수정할 때 상태값을 바꾸는 경우만 있지 않을까 생각되어서 patch로 하고 있습니다

2023-10-14 02:24 UTC, kthss01 commented on src/taxi/taxi.service.spec.ts
> +      .compile();
예제 코드를 따라 진행했었는데 이 부분은 생각하지 못해본 부분인거 같습니다
beforeEach에서 처리해야만 하는 이유는 없는거 같습니다

2023-10-14 02:25 UTC, kthss01 commented on src/taxi/taxi.service.spec.ts
> +    // TOBO 뭔가 이상함 그냥 plainToClass 안해도 no 같은거 안들어가야할거 같은데 들어감
확인했습니다 감사합니다

2023-10-14 03:53 UTC, kthss01 commented on src/taxi/taxi.service.spec.ts
> +    expect(createTaxi.driverNo).toBe(131112345678);
말씀하신 부분 이해했습니다 respitory.spect에서 테스트 진행할 수 있도락 하겠습니다

2023-10-14 05:07 UTC, kimseungbin commented on src/taxi/dto/response-taxi.dto.ts
> +  driverNo: number;
1:1 이면 개발 분량을 줄이기 위해서 합쳐버리는 것도 방법인거같습니다.
이름이나 설명에 driverLicense 라는 정보가 들어가면 좋을거같습니다.

2023-10-14 06:48 UTC, kthss01 commented on src/taxi/dto/response-taxi.dto.ts
> +  driverNo: number;
네 확인했습니다

2023-10-14 06:49 UTC, kimseungbin commented on src/taxi/taxi.service.spec.ts
> +      .compile();
이 부분때문에 테스트가 느려질 수 있을거같아요.

2023-10-14 06:51 UTC, kimseungbin commented on src/taxi/taxi.controller.ts
> +  }
운행상태 가 택시의 다른 정보와 속성이 다르기 때문에 분리가 필요할 것같습니다.

2023-10-14 12:13 UTC, Ooyd approved these changes

2023-10-14 15:23 UTC, kthss01 commented
> 전체적으로 모듈 이름이 단수처리되어있어 어색한 path 가 생성됩니다. taxis 로 전체 변경이 필요합니다.

말씀해주신데로 taxi -> taxis로 전체 변경을 진행하는게 좋을 거 같습니다

2023-10-14 15:23 UTC, kthss01 commented on src/taxi/taxi.service.spec.ts
> +  });
확인했습니다

2023-10-14 15:23 UTC, kthss01 commented on src/taxi/taxi.service.spec.ts
> +      .compile();
말씀하신 부분 이해했습니다

2023-10-15 01:49 UTC, junman95 commented on src/taxi/taxi.controller.ts
> +    @Body() taxiInfo: UpdateTaxiDto,
update-taxi dto파일을 보니 Nullable여부가 없었습니다(IsNotEmpty())
create-taxi dto처럼 의도되지 않은 빈 값이 들어오지 않도록 해야될 것 같습니다.

2023-10-15 01:54 UTC, junman95 approved these changes

2023-10-15 22:53 UTC, kthss01 commented on src/taxi/taxi.controller.ts
> +    @Body() taxiInfo: UpdateTaxiDto,
확인했습니다 감사합니다

2023-10-16 14:30 UTC, kthss01 commented on src/taxi/taxi.controller.ts
> +    @Body() taxiInfo: UpdateTaxiDto,
승빈님이 작업하신 방법으로 create-taxi dto를 parital로 extends 받아 해결하였습니다

2023-10-16 14:33 UTC, kthss01 commented on src/taxi/taxi.controller.ts
> +  }
운행상태에 대해서 현재 Call 도메인에서 관리되고 있는 것을 확인하였습니다 
이 부분에 있어서 좀더 협의가 필요할 것으로 보입니다

2023-10-16 14:38 UTC, kthss01 commented on src/taxi/taxi.controller.ts
> +  }
제가 확인을 잘못했습니다 현재 ERD Diagram 기준으로
Driver Table에서 status가 관리되고 있었고
말씀해주신데로 분리 작업을 진행하도록 하겠습니다

2023-10-17 02:00 UTC, kimseungbin requested changes

2023-10-17 02:00 UTC, kimseungbin commented on src/taxis/entities/taxi-status.entity.ts
> +    comment: 'PENDING | COMPLETE | ARRIVED | CANCELLED',
AVAILABLE, EN_ROUTE, OCCUPIED 가 enum 으로 들어가야할 것같습니다.
취소나 완료같은 경우엔 택시의 '현재' 상태가 아니라 운행 기록의 측면에서 가능한 상태로 보입니다.
추가적으로 해당 정보가 휘발성이 아니라면 OFF_DUTY 도 포함돼야하겠네요.

2023-10-17 02:00 UTC, kimseungbin commented on src/taxis/entities/taxi.entity.ts
> +  taxiStatus: TaxiStatus;
좋은 todo 처리인거같아요.

2023-10-17 02:00 UTC, kimseungbin commented on src/taxis/entities/taxi.entity.ts
> +  profileImg: string;
이미지 구현하려면 인프라 작업도 병행이 돼야하는데 꼭 필요한 부분인지 모르겠습니다.

2023-10-19 01:39 UTC, kimseungbin approved these changes

2023-10-19 06:13 UTC, merged