Feature/auth
HPlus1100/server pull request #21
Opened 2023-10-09 06:48 UTC by ghd64845

## Description
Driver 및 Customer 회원가입 추가
<br>

## Key Changes

<br>

## Issue Reference

> (Only on Fix and Hotfix branch)

## Package Change

> bcrypt 모듈 추가
> docker-compose tdd_server volumn 변경

<br>

## Checklist

- [x] Asignee를 같은 파트원으로 지정했나요?
- [x] Reviewer를 2명 이상 지정 했나요?
- [x] 코드의 엣지 케이스에 대해 충분히 고민 하셨나요?
- [x] conflict가 나지 않는지 확인 하셨나요?

2023-10-12 09:00 UTC, kimseungbin commented
`package.json` 에 변화가 생긴 게 아닌가요? PR 내용에는 없다고 적어주셨는데, 실제 코드에는 변경점이 있습니다.

2023-10-12 09:00 UTC, kimseungbin reviewed
package.json 에 변화가 생긴 게 아닌가요? PR 내용에는 없다고 적어주셨는데, 실제 코드에는 변경점이 있습니다.

2023-10-12 11:11 UTC, kimseungbin requested changes
테스트코드와 서비스코드가 동시에 변경되어 이게 테스트때문에 코드가 수정된건지 코드 수정하다가 테스트가 바뀐것인지 알기가 어렵습니다. 다음번엔 분할이 있었으면 합니다.

2023-10-12 11:11 UTC, kimseungbin commented on src/user/entity/user.entity.ts
> +import * as bcrypt from 'bcrypt'
`bcrypt` 사용하시는 이유가 있나요?
제가 인프라 세팅 때 없어서 현재 팀내에서 arm 으로 통일하기로 결정한건지를 모르겠네요.

2023-10-12 11:11 UTC, kimseungbin commented on .gitignore
`lock` 파일을 깃에서 빼는 변경 이유를 알 수 있을까요?

2023-10-12 11:11 UTC, kimseungbin commented on package.json
불필요한 변경사항입니다.

2023-10-12 11:11 UTC, kimseungbin commented on tsconfig.json
여기 역시 불필요한 코드 스타일 변경사항이 포함된거같습니다.

2023-10-12 11:11 UTC, kimseungbin commented on .vscode/settings.json
불필요한 파일이 공유되고 있습니다.

2023-10-12 14:12 UTC, ghd64845 commented on .gitignore
아 다시 추가해서 올렸습니다!

2023-10-12 14:20 UTC, ghd64845 commented on src/user/entity/user.entity.ts
> +import * as bcrypt from 'bcrypt'
아 저도 그부분은 간과하고 있었네요 arm환경에서 bcrypt를 사용시에 추가 작업이 필요한 것 떄문에 말씀하실 걸까요?

2023-10-13 01:25 UTC, kimseungbin commented on src/user/entity/user.entity.ts
> +import * as bcrypt from 'bcrypt'
네 맞습니다. 특별한 이유가 없으면 crypto 대신 bcrypt 를 쓸 필오가 없다고 생각합니다.

2023-10-13 11:42 UTC, kimseungbin commented
@ghd64845 하차로 인한 draft 화

2023-10-25 16:05 UTC, closed without merging

2023-10-25 16:05 UTC, junman95 commented
반영되지 않을 것 같아 Close 했습니다.