Feat/custom repo jest config
HPlus1100/server pull request #33
Opened 2023-10-12 10:34 UTC by junman95

## Description
* 서비스 테스트 코드 내에서 커스텀 레포지토리를 provider로 지정하기
<br>

## Key Changes
* 커스텀 레포지토리 in-memory db를 통한 provider 적용
* setupDataSource util 분리
<br>

## Checklist

- [ ] Asignee를 같은 파트원으로 지정했나요?
- [ ] Reviewer를 2명 이상 지정 했나요?
- [x] 코드의 엣지 케이스에 대해 충분히 고민 하셨나요?
- [x] conflict가 나지 않는지 확인 하셨나요?

2023-10-12 10:56 UTC, kimseungbin requested changes
merge commit 을 꼭 남기기로 약속한 것이 아니라면 불필요한 변경사항이 포함되어 가독성을 저해합니다.

2023-10-13 13:00 UTC, kimseungbin approved these changes

2023-10-14 11:56 UTC, Ooyd approved these changes

2023-10-14 15:05 UTC, kthss01 approved these changes

2023-10-15 03:39 UTC, kimseungbin commented
@junman95 병합하셔도 좋을거같습니다.

2023-10-15 12:54 UTC, merged