Feature/external api
HPlus1100/server pull request #41
Opened 2023-10-13 12:34 UTC by junman95

## Description
* 외부 API를 사용하기 위한 repository class 등록
<br>

## Key Changes
* local api(특정 위치정보) repository 생성
* path api(이동 정보) repository 생성
* repository 테스트 환경 구성
* setupDataSource 분리

<br>

## Issue Reference
* ConfigModule env 경로 이슈 : 루트 경로의 env파일만 읽어들임.

## Package Change
* pg-mem ^2.7.1 설치

<br>

## Checklist

- [ ] Asignee를 같은 파트원으로 지정했나요?
- [x] Reviewer를 2명 이상 지정 했나요?
- [ ] 코드의 엣지 케이스에 대해 충분히 고민 하셨나요?
- [x] conflict가 나지 않는지 확인 하셨나요?

2023-10-14 11:55 UTC, Ooyd commented on src/externalApi/local-api.repository.ts
> +    this.logger.log(this.httpService.axiosRef.defaults.headers.Authorization);
민감한 정보가 로깅으로 출력되는거같은데, 이렇게 하신 이유가 있으실까요?

2023-10-14 15:04 UTC, kthss01 commented on test/util/setupDataSource.ts
해당 부분 확인하였습니다 추후 merge 되면 taxi 도메인의 테스트도 setupDataSource를 사용하여 처리하도록 수정하겠습니다

2023-10-14 15:04 UTC, kthss01 submitted a review, later dismissed

2023-10-15 02:22 UTC, junman95 commented on src/externalApi/local-api.repository.ts
> +    this.logger.log(this.httpService.axiosRef.defaults.headers.Authorization);
아 코드 돌려보는 과정에서 찍었던 로그인데 제외토록하겠습니다!

2023-10-15 03:41 UTC, kimseungbin requested changes
다른 브랜치의 변경사항이 상당부분 포함되어 있어 해당 브랜치 병합 후 리베이스 한 다음 리뷰하는 것이 좋을거같습니다.

2023-10-16 16:32 UTC, junman95 commented
> 다른 브랜치의 변경사항이 상당부분 포함되어 있어 해당 브랜치 병합 후 리베이스 한 다음 리뷰하는 것이 좋을거같습니다.

이제 타 브랜치 변경사항 없습니다!! 리베이스도 했어요

2023-10-16 16:50 UTC, Ooyd approved these changes, later dismissed

2023-10-17 02:02 UTC, kimseungbin approved these changes, later dismissed

2023-10-19 10:23 UTC, kimseungbin commented
여유가 되신다면 #61 반영 후 병합 부탁드립니다.

2023-10-25 16:01 UTC, closed without merging