feature: jest-e2e path alias 설정
HPlus1100/server pull request #46
Opened 2023-10-13 19:25 UTC by Ooyd

# Description
jest-e2e path alias 설정

# Key Changes
절대경로 일부 미적용부분 적용완료

# Issue Reference

> (Delete if unnecessary)

# Package Change

> (Delete if unnecessary)

# Checklist

- [x] Asignee를 본인으로 지정하셨나요?
- [x] Reviewer를 2명 이상 지정 했나요?
- [] 코드의 엣지 케이스에 대해 충분히 고민 하셨나요?
- [x] conflict가 나지 않는지 확인 하셨나요?

2023-10-14 01:15 UTC, kimseungbin requested changes

2023-10-14 01:15 UTC, kimseungbin commented on test/jest-e2e.json
> +    "^@call/(.*)$": "<rootDir>/call/$1"
어 call 이 호출이 되나요? 아니면 `test/call` 이 따로 있으신건가요

2023-10-14 10:32 UTC, Ooyd commented on test/jest-e2e.json
> +    "^@call/(.*)$": "<rootDir>/call/$1"
아 호출되는부분 아닙니다.
package.json 참조해서 작성하다가 같이 넣었어요. 생각해봤는데 e2e에서는 필요없을거같은데 해당부분 수정하겠습니다!

2023-10-14 15:02 UTC, kthss01 approved these changes

2023-10-15 03:42 UTC, kimseungbin approved these changes

2023-10-15 07:06 UTC, merged