Feature/call
HPlus1100/server pull request #57
Opened 2023-10-16 13:05 UTC by junman95

# Description
* path api createCall 서비스에 적용

# Key Changes
* path api createCall 서비스에 적용
* jest config 생성( 상대경로 이슈 해결)
* createCall 테스트 케이스 수정
* path api entity 생성

# Issue Reference

> (Delete if unnecessary)

# Package Change
* jest -  config 경로설정

# Checklist

- [x] Asignee를 본인으로 지정하셨나요?
- [x] Reviewer를 2명 이상 지정 했나요?
- [x] 코드의 엣지 케이스에 대해 충분히 고민 하셨나요?
- [ ] conflict가 나지 않는지 확인 하셨나요?

2023-10-16 13:41 UTC, Ooyd commented on src/call/call.service.spec.ts
> +import { PathApiRepository } from '@/externalApi/path-api.repository';
package.json externalAPI가 등록 안된거같아요. 해당부분 확인한번 부탁드립니다.

2023-10-16 15:59 UTC, junman95 commented on package.json
> +}
왜 전부 업데이트 됐을까요?

2023-10-16 16:04 UTC, junman95 commented on src/call/call.service.spec.ts
> +import { PathApiRepository } from '@/externalApi/path-api.repository';
@가 src로 잡혀있습니다!

2023-10-19 09:13 UTC, kthss01 approved these changes, later dismissed

2023-10-19 10:33 UTC, kimseungbin requested changes
path 명이 단수로 되어있어 향후 RESTful 하지 않은 API 가 될 수 있습니다.

2023-10-19 10:33 UTC, kimseungbin commented on src/externalApi/local-api.repository.ts
> +  async getAxisbyAddress(address: string): Promise<unknown> {
코칭 받은 대로 이름 수정이 필요해보입니다.

2023-10-19 10:33 UTC, kimseungbin commented on src/externalApi/local-api.repository.spec.ts
> +  describe('AXIS 요청', () => {
axis 는 부적절해보입니다.
coordinates 나 address 로 수정하는게 어떨까요?

2023-10-19 10:33 UTC, kimseungbin commented on src/externalApi/path-api.entity.ts
> +}
Api 라는 명칭이 중복적인 것 같습니다. 다른 Entity 도 모두 API 호출에 관련된 Entity 이기 때문입니다.

2023-10-19 10:33 UTC, kimseungbin commented on src/externalApi/path-api.repository.ts
> +    return res;
왜 여러 요금을 합산해야하는지 설명이 부족해보입니다.

2023-10-19 10:33 UTC, kimseungbin commented on jest.config.js
> +};
기존 config 는 삭제하지 않고 새로 만들기만 하는건가요?

2023-10-20 10:17 UTC, junman95 commented on jest.config.js
> +};
해당부분은, 성준님의 코멘트에따라서 package.json에 작성했습니다!

2023-10-20 10:18 UTC, junman95 commented on src/externalApi/path-api.repository.ts
> +    return res;
톨게이트 비용을 합산해 주어야합니다!!

2023-10-20 10:20 UTC, kimseungbin commented on src/externalApi/path-api.repository.ts
> +    return res;
아하 그래서 비용이 1개가 아니었군요.
코드상으로는 해당 내용을 파악하기가 어려운데 주석 등으로 설명이 들어가면 좋을 것같습니다.

2023-10-20 10:21 UTC, kimseungbin commented on jest.config.js
> +};
그러면 이 커밋은 지우는게 낫지 않을까요?
해당 파일을 만들었다가 삭제했다는 것이 꼭 기록으로 남을만한지 모르겠습니다.

2023-10-20 11:10 UTC, kimseungbin commented on src/externalApi/local-api.repository.spec.ts
> +  describe('AXIS 요청', () => {
그 scissors 나 coordinates 같은 단어는 항상 복수로 쓰입니다!

2023-10-25 16:01 UTC, merged